Team.create(name: 'Alemania', coach: 'Joachim Low', group: 'G')
Team.create(name: 'Argelia', coach: 'Vahid Halilhodzic', group: 'H')
Team.create(name: 'Argentina', coach: 'Alejandro Sabella', group: 'F')
Team.create(name: 'Australia', coach: 'Ange Postecoglou', group: 'B')
Team.create(name: 'Belgica', coach: 'Marc Wilmots', group: 'H')
Team.create(name: 'Bosnia y Herzegovina', coach: 'Safet Susic', group: 'F')
Team.create(name: 'Brasil', coach: 'Luiz Felipe Scolari', group: 'A')
Team.create(name: 'Camerun', coach: 'Volker Finke', group: 'A')
Team.create(name: 'Chile', coach: 'Jorge Sampaoli', group: 'B')
Team.create(name: 'Colombia', coach: 'Jose Pekerman', group: 'C')
Team.create(name: 'Corea del Sur', coach: 'Hong Myung-bo', group: 'H')
Team.create(name: 'Costa de Marfil', coach: 'Sabri Lamouchi', group: 'C')
Team.create(name: 'Costa Rica', coach: 'Jorge Luis Pinto', group: 'D')
Team.create(name: 'Croacia', coach: 'Niko Kovac', group: 'A')
Team.create(name: 'Ecuador', coach: 'Reinaldo Rueda', group: 'E')
Team.create(name: 'Espana', coach: 'Vicente del Bosque', group: 'B')
Team.create(name: 'Estados Unidos', coach: 'Jurgen Klinsmann', group: 'G')
Team.create(name: 'Francia', coach: 'Didier Deschamps', group: 'E')
Team.create(name: 'Ghana', coach: 'James Kwesi Appiah', group: 'G')
Team.create(name: 'Grecia', coach: 'Fernando Santos', group: 'C')
Team.create(name: 'Holanda', coach: 'Louis van Gaal', group: 'B')
Team.create(name: 'Honduras', coach: 'Luis Fernando Suarez', group: 'E')
Team.create(name: 'Inglaterra', coach: 'Roy Hodgson', group: 'D')
Team.create(name: 'Iran', coach: 'Carlos Queiroz', group: 'F')
Team.create(name: 'Italia', coach: 'Cesare Prandelli', group: 'D')
Team.create(name: 'Japon', coach: 'Alberto Zaccheroni', group: 'C')
Team.create(name: 'Mexico', coach: 'Miguel Herrera', group: 'A')
Team.create(name: 'Nigeria', coach: 'Stephen Keshi', group: 'F')
Team.create(name: 'Portugal', coach: 'Paulo Bento', group: 'G')
Team.create(name: 'Rusia', coach: 'Fabio Capello', group: 'H')
Team.create(name: 'Suiza', coach: 'Ottmar Hitzfeld', group: 'E')
Team.create(name: 'Uruguay', coach: 'Oscar Washington Tabarez', group: 'D')

Arena.create(name: 'Arena Mineirao', city: 'Belo Horizonte', capacity: 69950)
Arena.create(name: 'Estadio Mane Garrincha', city: 'Brasilia', capacity: 70807)
Arena.create(name: 'Arena Pantanal', city: 'Cuiaba', capacity: 42500)
Arena.create(name: 'Arena da Baixada', city: 'Curitiba', capacity: 41375)
Arena.create(name: 'Estadio Castelao', city: 'Fortaleza', capacity: 60000)
Arena.create(name: 'Estadio Vivaldo Lima', city: 'Manaos', capacity: 50000)
Arena.create(name: 'Estadio das Dunas', city: 'Natal', capacity: 45000)
Arena.create(name: 'Estadio Beira-Rio', city: 'Porto Alegre', capacity: 60000)
Arena.create(name: 'Arena Pernambuco', city: 'Recife', capacity: 46154)
Arena.create(name: 'Estadio Maracana', city: 'Rio de Janeiro', capacity: 76525)
Arena.create(name: 'Arena Fonte Nova', city: 'Salvador', capacity: 50433)
Arena.create(name: 'Arena de Sao Paulo', city: 'San Pablo', capacity: 65281)